name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build essentials
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Install C++ development tools
      run: sudo apt-get install -y g++ cmake
      
    - name: Install libcurl
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: Execute prework
      run: ./prework.sh

    - name: CMake
      run: cmake .

    - name: Make
      run: make

    - name: Print version
      run: ./out/lvpnfu -v

    - name: Print help
      run: ./out/lvpnfu -h
